// Lovable integration removed — shim to preserve imports.
// The original file was auto-generated by Lovable and relied on @lovable.dev.
// We now re-route consumers to the internal `auth` module which uses Supabase.

export { auth as lovable } from "../integrations/auth";
